### ISSUE TITLE
Prediction intervals

### ISSUE THREAD

**Issue by rmlopes** [facebookincubator/bootstrapped#8]
An implementation of prediction intervals  computation (instead of confidence intervals) would be much appreciated. Is it possible to add the functionality to the library, or would it be out of scope? 

I am assuming there is some core functionality shared between the two (CIs and PIs), at least the bootstrapping itself should be the same, and then there are some differences in the calculations of the intervals.

I have found [this explanation](https://stats.stackexchange.com/questions/226565/bootstrap-prediction-interval) useful.

**Comment by spencebeecher** [comment]
Thanks for the feedback @rmlopes - let me have a look at this today. Apologies for the delay in response!

**Comment by spencebeecher** [comment]
Hi @rmlopes - do you have an approach in mind? The bootstrapped library relies on the input data being pre-determined before resampling. This is an assumption made so that the resampling can be done with numpy arrays. 

I could write a bootstrap that will take in an arbitrary function and returns the bootstrap result (this will be just a tiny bit fancier then a for loop). 

If you have a specific implementation I am definitely open to it and would gladly take a pull request.
